export const defaultTheme = {
  fontFamily: '"Inter", "Arial", sans-serif',
  height: '100%',
  paddingLeft: '90px',
  paddingRight: '90px',
  ColorMain: '#ffffff',
  width: '1280px',
  ColorCardMain: '#e1edce',
  ColorCardNegative: '#f8ddd7',
  ColorMarker: '#88aa4d',
  ColorMarkerNegative: '#f75531',
  ColorButton: '#fc9b27',
  ColorButtonActive: '#fc7427',
  ColorAbout: '#d8ecfe',
  colorText: '#333333',
  fontSize: '18px',
  lineHeight: '27px',
  fontWeight: '400',
};
