export const defaultTheme = {
  fontFamily: '"Inter", "Arial", sans-serif',
  height: '100%',
  paddingLeft: '90px',
  paddingRight: '90px',
  backgroundColorMain: '#ffffff',
  width: '1280px',
  backgroundColorCardMain: '#e1edce',
  backgroundColorCardNegative: '#f8ddd7',
  backgroundColorMarker: '#88aa4d',
  backgroundColorMarkerNegative: '#f75531',
  backgroundColorButton: '#fc9b27',
  backgroundColorButtonActive: '#fc7427',
  backgroundColorAbout: '#d8ecfe',
  colorText: '#333333',
  fontSize: '18px',
  lineHeight: '27px',
  fontWeight: '400',
};
